### ISSUE TITLE
mongodb requirement

### ISSUE THREAD

**Issue by kermitt2** [Vi-dot/grobid-smecta#2]
To simplify the usage/portability of the tool, what about working with the files directly by putting the metadata in the TEI headers of the training files, instead of using mongodb?

**Comment by Vi-dot** [comment]
The idea is good, but if we do that, we lost history data for `Trainer` part. For example we don't know if TrainingFiles are all validated or not for one particular training.

**Comment by Vi-dot** [comment]
Replaced by [Nitrite](http://www.dizitart.org/nitrite-database/), NoSQL embedded, with POJO system.
NoSQL is better than flat files, if later we would like to do search/filter on all training files.
And Nitrite offers a way to export data into JSON file.
