### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by kaplun** [Vi-dot/grobid-smecta#3]
It would be great to have some screenshots available about what grobid-smecta is.
We are currently looking for a web interface on top of Grobid and this project looks quite promising.

**Comment by kermitt2** [comment]
I have made one but probably not very helpful and informative as compared to a demo with the astro parser. 
![screenshot from 2017-03-13 21-56-30](https://user-images.githubusercontent.com/2340795/27833703-321db2da-60d4-11e7-9529-25a0e64ad6db.png)

**Comment by Vi-dot** [comment]
Done in [README.md](https://github.com/Vi-dot/grobid-smecta/blob/master/README.md)
