### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kaplun** [Vi-dot/grobid-smecta#4]
I am trying to install grobid-smecta.

> Set your paths in properties file grobid-smecta/src/main/resources/grobid-smecta.properties 

Assuming no experience with Java project source code, what shall I put inside this file? 

> In your project, make your Trainer extends SmectaAbstractTrainer 
> Add dependency in grobid-YOUR_MODULE/pom.xml

What do you mean by my project? How can I simply install smecta to point to the local Grobid instance?

**Comment by Vi-dot** [comment]
Hello,

> What do you mean by my project? How can I simply install smecta to point to the local Grobid instance?

By "your project", I mean a grobid submodule. As example, we have a submodule of grobid called `grobid-astro` which is working around astronomical references. Other example of submodule : `grobid-quantities`.

If you want to train fulltext models inside grobid, I guess you have to link `grobid-smecta` to `grobid-trainer`. But you should not do it, grobid fulltext is already trained.

I don't know what's your aim with grobid, but you may need to create your own submodule project like `grobid-hep`.

> Assuming no experience with Java project source code, what shall I put inside this file?

You only need to edit entries already present in the file `grobid-smecta.properties` according to your configuration :
- If you have a special host/port for MongoDB, then edit `grobid.smecta.mongodb.*`
- Then, and it's mandatory to be edited, the path to the grobid module you would like to train, you have to edit `grobid.smecta.trainingFiles.mainDirectory`
- Finally, if you have grobid installed somewhere else than in the previous folder of grobid-smecta, you need to edit `grobid.home` and `grobid.properties`.

> In your project, make your Trainer extends SmectaAbstractTrainer

In fact, now you don't need any more to make your Trainer extends from SmectaAbstractTrainer. Your Trainer can extend from AbstractTrainer (grobid-core), it's enough.
