### ISSUE TITLE
Integrate the application as a single web application

### ISSUE THREAD

**Issue by lfoppiano** [Vi-dot/grobid-smecta#5]
Would be nice to converge, since the application is rather simpler, to have a single application running with Jetty/Tomcat instead of depending of node js.

**Comment by Vi-dot** [comment]
As we are using angular-cli, we can't avoid completely node js.
But now, all client part is hidden behind maven processes.
Node, npm, angular-cli and client dependencies are installed during `mvn install` phase.
And to start client server, you can call `mvn exec:exec -Pclient-dev` or `mvn exec:exec -Pclient-prod`
